### PR TITLE
Add deps.edn.

### PR DESCRIPTION
**Pull request by davidneu**

### CODE REVIEW

**Comment by dm3** [comment]
Could you please clarify what's the benefit of having the `deps.edn` in addition to `project.clj`? Does it make sense to get rid of Leiningen in favor of the Clj tool completely? Is it necessary to duplicate the dependency declarations?

**Comment by davidneu** [comment]
Having both deps.edn and project.clj will allow projects that are currently using Leiningen to continue to do so, and will support the use of the Clojure command tools by new projects or existing projects that want to transition.  I'm not aware of any way for Leiningen to read dependencies from deps.edn files or the Clojure command tools to read them from project.clj files, so I think you'll want to have them both.  FWIW, clj-time has both deps.edn and project.clj.

**Comment by dm3** [comment]
Fair enough. I trust you tested the thing works.

**Comment by davidneu** [comment]
Yes, I've tested it - thanks for accepting the PR.

**Pull request merged**
